name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: truffleruby
            rubygems: default
          - ruby: truffleruby+graalvm
            rubygems: default
          - ruby: jruby
            rubygems: default
          - ruby: "2.5"
            rubygems: "2.6.9"
            rake_task: "rubocop test"
          - ruby: "2.6"
            rubygems: default
          - ruby: "2.7"
            rubygems: default
          - ruby: "3.0"
            rubygems: default
          - ruby: "3.1"
            rubygems: default
            coverage: "yes"
          - ruby: "3.2"
            rubygems: default
    env:
      RUBYOPT: --enable-frozen-string-literal
      COVERAGE: ${{ matrix.coverage }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake ${{ matrix.rake_task }}
      - name: Build gem
        run: gem build *.gemspec
  tests:
    needs:
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
